(()=>{var __webpack_modules__=({"./resources/js/theme.js":/*!*******************************!*\
!*** ./resources/js/theme.js ***!
\*******************************/(()=>{(function($){"use strict";if($(".scroll-to-target").length){$(".scroll-to-target").on("click",function(){var target=$(this).attr("data-target");$("html, body").animate({scrollTop:$(target).offset().top},1000);return false;});}
if($(".video-popup").length){$(".video-popup").magnificPopup({disableOn:700,type:"iframe",mainClass:"mfp-fade",removalDelay:160,preloader:true,fixedContentPos:false});}
function dynamicCurrentMenuClass(selector){var FileName=window.location.href.split("/").reverse()[0];selector.find("li").each(function(){var anchor=$(this).find("a");if($(anchor).attr("href")==FileName){$(this).addClass("current");}});selector.children("li").each(function(){if($(this).find(".current").length){$(this).addClass("current");}});if(""==FileName){selector.find("li").eq(0).addClass("current");}}
if($(".main-menu__list").length){var mainNavUL=$(".main-menu__list");dynamicCurrentMenuClass(mainNavUL);}
if($(".main-menu").length&&$(".mobile-nav__container").length){var navContent=document.querySelector(".main-menu").innerHTML;var mobileNavContainer=document.querySelector(".mobile-nav__container");mobileNavContainer.innerHTML=navContent;}
if($(".sticky-header__content").length){var _navContent=document.querySelector(".main-menu").innerHTML;var _mobileNavContainer=document.querySelector(".sticky-header__content");_mobileNavContainer.innerHTML=_navContent;}
if($(".mobile-nav__container .main-menu__list").length){var dropdownAnchor=$(".mobile-nav__container .main-menu__list .dropdown > a");dropdownAnchor.each(function(){var self=$(this);var toggleBtn=document.createElement("BUTTON");toggleBtn.setAttribute("aria-label","dropdown toggler");toggleBtn.innerHTML="<i class='fa fa-angle-down'></i>";self.append(function(){return toggleBtn;});self.find("button").on("click",function(e){e.preventDefault();var self=$(this);self.toggleClass("expanded");self.parent().toggleClass("expanded");self.parent().parent().children("ul").slideToggle();});});}
if($(".mobile-nav__toggler").length){$(".mobile-nav__toggler").on("click",function(e){e.preventDefault();$(".mobile-nav__wrapper").toggleClass("expanded");});}
if($(".search-toggler").length){$(".search-toggler").on("click",function(e){e.preventDefault();$(".search-popup").toggleClass("active");});}
if($(".odometer").length){$(".odometer").appear(function(e){var odo=$(".odometer");odo.each(function(){var countNumber=$(this).attr("data-count");$(this).html(countNumber);});});}
if($(".wow").length){var wow=new WOW({boxClass:"wow",animateClass:"animated",mobile:true,live:true});wow.init();}
if($("#donate-amount__predefined").length){var donateInput=$("#donate-amount");$("#donate-amount__predefined").find("li").on("click",function(e){e.preventDefault();var amount=$(this).find("a").text();donateInput.val(amount);$("#donate-amount__predefined").find("li").removeClass("active");$(this).addClass("active");});}
$("#accordion .collapse").on("shown.bs.collapse",function(){$(this).prev().addClass("active");$(this).prev().parent().addClass("active");});$("#accordion .collapse").on("hidden.bs.collapse",function(){$(this).prev().removeClass("active");$(this).prev().parent().removeClass("active");});$("#accordion").on("hide.bs.collapse show.bs.collapse",function(e){$(e.target).prev().find("i:last-child").toggleClass("fa-plus fa-minus");});$(window).on("load",function(){if($(".preloader").length){$(".preloader").fadeOut();}
var swiperElm=document.querySelectorAll(".thm-swiper__slider");swiperElm.forEach(function(swiperelm){var swiperOptions=JSON.parse(swiperelm.dataset.swiperOptions);var thmSwiperSlider=new Swiper(swiperelm,swiperOptions);});if($("#testimonials-one__thumb").length){var testimonialsThumb=new Swiper("#testimonials-one__thumb",{slidesPerView:3,spaceBetween:20,speed:1400,watchSlidesVisibility:true,watchSlidesProgress:true,autoplay:{delay:5000}});var testimonialsMeta=new Swiper("#testimonials-one__meta",{slidesPerView:1,spaceBetween:0,speed:1400,watchSlidesVisibility:true,watchSlidesProgress:true,autoplay:{delay:5000}});var testimonialsCarousel=new Swiper("#testimonials-one__carousel",{observer:true,observeParents:true,speed:1400,mousewheel:true,slidesPerView:1,autoplay:{delay:5000},pagination:{el:"#testimonials-one__swiper-pagination",type:"bullets",clickable:true},thumbs:{swiper:testimonialsThumb}});testimonialsCarousel.controller.control=testimonialsMeta;testimonialsMeta.controller.control=testimonialsCarousel;}
if($(".circle-progress").length){$(".circle-progress").appear(function(){var circleProgress=$(".circle-progress");circleProgress.each(function(){var progress=$(this);var progressOptions=progress.data("options");progress.circleProgress(progressOptions);});});}});$(window).on("scroll",function(){if($(".stricked-menu").length){var headerScrollPos=130;var stricky=$(".stricked-menu");if($(window).scrollTop()>headerScrollPos){stricky.addClass("stricky-fixed");}else if($(this).scrollTop()<=headerScrollPos){stricky.removeClass("stricky-fixed");}}
if($(".scroll-to-top").length){var strickyScrollPos=100;if($(window).scrollTop()>strickyScrollPos){$(".scroll-to-top").fadeIn(500);}else if($(this).scrollTop()<=strickyScrollPos){$(".scroll-to-top").fadeOut(500);}}});})(jQuery);}),"./resources/sass/main.scss":/*!**********************************!*\
!*** ./resources/sass/main.scss ***!
\**********************************/((__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";__webpack_require__.r(__webpack_exports__);})});var __webpack_module_cache__={};function __webpack_require__(moduleId){var cachedModule=__webpack_module_cache__[moduleId];if(cachedModule!==undefined){return cachedModule.exports;}
var module=__webpack_module_cache__[moduleId]={exports:{}};__webpack_modules__[moduleId](module,module.exports,__webpack_require__);return module.exports;}
__webpack_require__.m=__webpack_modules__;(()=>{var deferred=[];__webpack_require__.O=(result,chunkIds,fn,priority)=>{if(chunkIds){priority=priority||0;for(var i=deferred.length;i>0&&deferred[i-1][2]>priority;i--)deferred[i]=deferred[i-1];deferred[i]=[chunkIds,fn,priority];return;}
var notFulfilled=Infinity;for(var i=0;i<deferred.length;i++){var[chunkIds,fn,priority]=deferred[i];var fulfilled=true;for(var j=0;j<chunkIds.length;j++){if((priority&1===0||notFulfilled>=priority)&&Object.keys(__webpack_require__.O).every((key)=>(__webpack_require__.O[key](chunkIds[j])))){chunkIds.splice(j--,1);}else{fulfilled=false;if(priority<notFulfilled)notFulfilled=priority;}}
if(fulfilled){deferred.splice(i--,1)
result=fn();}}
return result;};})();(()=>{__webpack_require__.o=(obj,prop)=>(Object.prototype.hasOwnProperty.call(obj,prop))})();(()=>{__webpack_require__.r=(exports)=>{if(typeof Symbol!=='undefined'&&Symbol.toStringTag){Object.defineProperty(exports,Symbol.toStringTag,{value:'Module'});}
Object.defineProperty(exports,'__esModule',{value:true});};})();(()=>{var installedChunks={"/js/theme":0,"css/main":0};__webpack_require__.O.j=(chunkId)=>(installedChunks[chunkId]===0);var webpackJsonpCallback=(parentChunkLoadingFunction,data)=>{var[chunkIds,moreModules,runtime]=data;var moduleId,chunkId,i=0;for(moduleId in moreModules){if(__webpack_require__.o(moreModules,moduleId)){__webpack_require__.m[moduleId]=moreModules[moduleId];}}
if(runtime)var result=runtime(__webpack_require__);if(parentChunkLoadingFunction)parentChunkLoadingFunction(data);for(;i<chunkIds.length;i++){chunkId=chunkIds[i];if(__webpack_require__.o(installedChunks,chunkId)&&installedChunks[chunkId]){installedChunks[chunkId][0]();}
installedChunks[chunkIds[i]]=0;}
return __webpack_require__.O(result);}
var chunkLoadingGlobal=self["webpackChunk"]=self["webpackChunk"]||[];chunkLoadingGlobal.forEach(webpackJsonpCallback.bind(null,0));chunkLoadingGlobal.push=webpackJsonpCallback.bind(null,chunkLoadingGlobal.push.bind(chunkLoadingGlobal));})();__webpack_require__.O(undefined,["css/main"],()=>(__webpack_require__("./resources/js/theme.js")))
var __webpack_exports__=__webpack_require__.O(undefined,["css/main"],()=>(__webpack_require__("./resources/sass/main.scss")))
__webpack_exports__=__webpack_require__.O(__webpack_exports__);})();